apiVersion: v1
kind: Namespace
metadata:
  name: vote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-db-deployment
  namespace: vote
  labels:
    app: voting-app
    type: db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting-app
      name: db-pod
  template:
    metadata:
      name: postgres-pod
      labels:
        app: voting-app
        name: db-pod
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          env:
            - name: POSTGRES_USER
              value: postgres
            - name:  POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.125"
            limits:
              memory: "265Mi"
              cpu: "0.250"
      volumes:
        - name: db-data
          emptyDir: {}
