apiVersion: v1
kind: Namespace
metadata:
  name: vote
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: voting-app
    name: db-pod
