apiVersion: v1
kind: Namespace
metadata:
  name: vote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-redis-deployment
  namespace: vote
  labels:
    app: voting-app
    type: redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting-app
      name: redis-pod
  template:
    metadata:
      name: redis-pod
      labels:
        app: voting-app
        name: redis-pod
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.125"
            limits:
              memory: "265Mi"
              cpu: "0.250"
          volumeMounts:
            - mountPath: /data
              name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {}
