apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: vote
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
  selector:
    app: voting-app
    name: result-pod
