apiVersion: v1
kind: Namespace
metadata:
  name: vote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-result-deployment
  namespace: vote
  labels:
    app: voting-app
    type: result
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting-app
      name: result-pod
  template:
    metadata:
      name: result-pod
      labels:
        app: voting-app
        name: result-pod
    spec:
      containers:
        - name: result
          image: muhmdraouf/voting_app_result
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.125"
            limits:
              memory: "265Mi"
              cpu: "0.250"
