apiVersion: v1
kind: Namespace
metadata:
  name: vote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-voting-deployment
  namespace: vote
  labels:
    app: voting-app
    type: voting
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting-app
      name: voting-pod
  template:
    metadata:
      name: voting-pod
      labels:
        app: voting-app
        name: voting-pod
    spec:
      containers:
        - name: voting
          image: muhmdraouf/voting_app_vote
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.250"
            limits:
              memory: "1Gi"
              cpu: "0.512"
