apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: vote
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    app: voting-app
    name: voting-pod
