apiVersion: v1
kind: Namespace
metadata:
  name: vote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-worker-deployment
  namespace: vote
  labels:
    app: voting-app
    type: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting-app
      name: worker-pod
  template:
    metadata:
      name: worker-pod
      labels:
        app: voting-app
        name: worker-pod
    spec:
      containers:
        - name: worker
          image: muhmdraouf/voting_app_worker
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.250"
            limits:
              memory: "1Gi"
              cpu: "0.512"
